// react/src/components/ListLooping.tsx
const cats = [
  { id: "J---aiyznGQ", name: "Keyboard Cat" },
  { id: "z_AbfPXTKms", name: "Maru" },
  { id: "OUtn3pvWmpg", name: "Henri The Existential Cat" },
];

const ListLooping = () => {
  return (
    <>
      <h1>The Famous Cats of YouTube</h1>
      <ul>
        {cats.map(({ id, name }, i) => (
          <li key={id}>
            <a href={`https://www.youtube.com/watch?v=${id}`} target="_blank">
              {i + 1}: {name}
            </a>
          </li>
        ))}
      </ul>
    </>
  );
};

export default ListLooping;

// vue-nuxt/components/ListLooping.vue
<script lang='ts'>
export default {
	data() {
		return {
			cats: [
				{ id: 'J---aiyznGQ', name: 'Keyboard Cat' },
				{ id: 'z_AbfPXTKms', name: 'Maru' },
				{ id: 'OUtn3pvWmpg', name: 'Henri The Existential Cat' }
			]
		}
	}
}

</script>

<template>
	<h1>The Famous Cats of YouTube</h1>
	<ul>
		<li v-for="(cat, index) of cats" :key="cat.id">
			<a target="_blank" :href="'https://www.youtube.com/watch?v=' + cat.id">
				{{ index + 1 }}: {{ cat.name }}
			</a>
		</li>
	</ul>
</template>
