// vue/sections/Navbar.vue

<template>
		<nav class="links">
			<button @click="() => handleSwitch(0)">Hello World</button>
			<button @click="() => handleSwitch(1)">Styling</button>
			<button @click="() => handleSwitch(2)">Nesting Components</button>
			<button @click="() => handleSwitch(3)">Props</button>
			<button @click="() => handleSwitch(4)">HTML Tags</button>
			<button @click="() => handleSwitch(5)">Basic Variables</button>
			<button @click="() => handleSwitch(6)">Dependent Variables</button>
			<button @click="() => handleSwitch(7)">Conditional Rendering</button>
			<button @click="() => handleSwitch(8)">List Looping</button>
		</nav>
</template>

// react/src/containers/Navbar/Navbar.tsx
import { Components } from "../../../pages";
import styles from "./Navbar.module.css";

interface NavbarProps {
  action: (option: Components) => void;
}

const Navbar = ({ action }: NavbarProps) => {
  return (
    <nav className={styles.links}>
      <button onClick={() => action(Components.HelloWorld)}>Hello World</button>
      <button onClick={() => action(Components.Styling)}>Styling</button>
      <button onClick={() => action(Components.NestingComponents)}>
        Nesting Components
      </button>
      <button onClick={() => action(Components.Props)}>Props</button>
      <button onClick={() => action(Components.HTML)}>HTML Tags</button>
      <button onClick={() => action(Components.BasicVariables)}>
        Basic Variables
      </button>
      <button onClick={() => action(Components.DependentVariables)}>
        Dependent Variables
      </button>
      <button onClick={() => action(Components.ConditionalRendering)}>
        Conditional Rendering
      </button>
      <button onClick={() => action(Components.ListLooping)}>
        List Looping
      </button>
      <button onClick={() => action(Components.TypingAnimation)}>
        Rainbow Typewriter
      </button>
    </nav>
  );
};

export default Navbar;
