// solid/src/components/NestingComponents/NestingComponents.tsx
import { Component, JSX } from "solid-js";
import Nested from "./Nested";

const styles: JSX.CSSProperties = {
  "color": "purple",
  "font-family": "'Comic Sans MS', cursive",
  "font-size": "2em",
};

const NestingComponents: Component = () => {
  return (
    <>
      <p style={styles}>These styles...</p>
      <Nested />
    </>
  );
};

export default NestingComponents;

// vue/src/components/NestingComponents.vue
<script lang="ts">
import Unstyled from "./child/Unstyled.vue";

export default {
  components: {
    Unstyled,
  },
};
</script>

<template>
  <div>
    <p class="text">These styles...</p>
    <Unstyled />
  </div>
</template>

<style scoped>
.text {
  color: purple;
  font-family: "Comic Sans MS", cursive;
  font-size: 2em;
}
</style>
