// angular/src/app/nesting-components/nesting-components.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-nesting-components',
  template: `
    <p>These styles</p>
    <app-nested-component></app-nested-component>
  `,
  styles: [
    `
      p {
        color: purple;
        font-family: 'Comic Sans MS', cursive;
        font-size: 2em;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NestingComponentsComponent {}

<p>These styles</p>
<app-nested-component></app-nested-component>

// vue/src/components/NestingComponents.vue
<script lang="ts">
import Unstyled from "./child/Unstyled.vue";

export default {
  components: {
    Unstyled,
  },
};
</script>

<template>
  <div>
    <p class="text">These styles...</p>
    <Unstyled />
  </div>
</template>

<style scoped>
.text {
  color: purple;
  font-family: "Comic Sans MS", cursive;
  font-size: 2em;
}
</style>
