// qwik/src/sections/Navbar/Navbar.tsx
import { component$, Host, useScopedStyles$ } from "@builder.io/qwik";
import { usePage } from "@builder.io/qwik-city";
import { Components, componentsList, getComponentTitle } from "../../layouts/default/default";
import styles from "./Navbar.css?inline";

export interface NavbarProps {
  currentComponent: Components;
  menuOpen: boolean;
  action: (option?: Components) => void;
}

const Navbar = component$<NavbarProps>(
  (props) => {
    const { currentComponent, menuOpen, action } = props;

    useScopedStyles$(styles);
    const page = usePage();
    //const navIndex = usePageIndex();
    if (!page) {
      return null;
    }

    return (
      <Host class="navbar">
        <nav class="links" style={menuOpen ? { display: "flex" } : {}}>
          <div class="close" onClick$={() => action()}>
            <div>x</div>
          </div>
          {componentsList.map((component) => (
            <button
              type="button"
              style={
                component === currentComponent
                  ? { backgroundColor: "rgb(56, 78, 189)" }
                  : {}
              }
              onClick$={() => action(component)}
            >
              {getComponentTitle(component)}
            </button>
          ))}
        </nav>
      </Host>
    );
  },
  { tagName: "aside" }
);

export default Navbar;

// react/src/sections/Navbar/Navbar.tsx
import { CSSProperties, useCallback } from "react";
import { Components, componentsList, getComponentTitle } from "../../../pages";
import styles from "./Navbar.module.css";

export interface NavbarProps {
  currentComponent: Components;
  menuOpen: boolean;
  action: (option?: Components) => void;
}

const Navbar = ({ currentComponent, menuOpen, action }: NavbarProps) => {

  const checkActiveBackground = useCallback(
    (component: Components): CSSProperties => {
      if (currentComponent === component)
        return { backgroundColor: "rgb(56, 78, 189)" };
      return {};
    },
    [currentComponent]
  );

  return (
    <nav className={styles.links} style={menuOpen ? { display: "flex" } : {}}>
      <div className={styles.close} onClick={() => action()}>
        <div>x</div>
      </div>
      {componentsList.map((component) => (
        <button
          key={`link-${component}`}
          type="button"
          style={checkActiveBackground(component)}
          onClick={() => action(component)}
        >
          {getComponentTitle(component)}
        </button>
      ))}
    </nav>
  );
};

export default Navbar;
