// solid/src/components/BasicVariables/BasicVariables.tsx
import { Component, createSignal } from "solid-js";

const BasicVariables: Component = () => {
  const [count, setCount] = createSignal(0);

  function handleClick() {
    setCount(count() + 1);
  }
  return (
    <button onClick={handleClick}>
      Clicked {count()} {count() === 1 ? "time" : "times"}
    </button>
  );
};

export default BasicVariables;

// react-next/src/components/BasicVariables/BasicVariables.tsx
import { useState } from "react";

const BasicVariables: React.FC = () => {
  const [count, setCount] = useState(0);

  function handleClick() {
    setCount(count + 1);
  }
  return (
    <button onClick={handleClick}>
      Clicked {count} {count === 1 ? "time" : "times"}
    </button>
  );
};

export default BasicVariables;
