// web/src/components/react/BasicVariables.tsx
/** @jsxImportSource react */
import React from "react";
import { useState } from "react";

const BasicVariables = () => {
  const [count, setCount] = useState(0);

  function handleClick() {
    setCount(count + 1);
  }
  return (
    <button onClick={handleClick}>
      Clicked {count} {count === 1 ? "time" : "times"}
    </button>
  );
};

export default BasicVariables;

// web/src/components/solid/BasicVariables.tsx
/** @jsxImportSource solid-js */
import { Component, createSignal } from "solid-js";

const BasicVariables: Component = () => {
  const [count, setCount] = createSignal(0);

  function handleClick() {
    setCount(count() + 1);
  }
  return (
    <button onClick={handleClick}>
      Clicked {count()} {count() === 1 ? "time" : "times"}
    </button>
  );
};

export default BasicVariables;
