// solid/src/components/DependentVariables/DependentVariables.tsx
import { Component, createEffect, createSignal } from "solid-js";

const DependentVariables: Component = () => {
  const [count, setCount] = createSignal(1);
  const [doubled, setDoubled] = createSignal(count() * 2);
  const [quadrupled, setQuadrupled] = createSignal(doubled() * 2);

  createEffect(() => {
    setDoubled(count() * 2);
    setQuadrupled(doubled() * 2);
  });

  function handleClick() {
    setCount(count() + 1);
  }

  return (
    <>
      <button onClick={handleClick}>Count: {count}</button>
      <p>
        {count} * 2 = {doubled}
      </p>
      <p>
        {doubled} * 2 = {quadrupled}
      </p>
    </>
  );
};

export default DependentVariables;

// react-next/src/components/DependentVariables/DependentVariables.tsx
import { useEffect, useState } from "react";

const DependentVariables: React.FC = () => {
  const [count, setCount] = useState(1);
  const [doubled, setDoubled] = useState(count * 2);
  const [quadrupled, setQuadrupled] = useState(doubled * 2);

  useEffect(() => {
    setDoubled(count * 2);
    setQuadrupled(doubled * 2);
  }, [count, doubled]);

  function handleClick() {
    setCount(count + 1);
  }

  return (
    <>
      <button onClick={handleClick}>Count: {count}</button>
      <p>
        {count} * 2 = {doubled}
      </p>
      <p>
        {doubled} * 2 = {quadrupled}
      </p>
    </>
  );
};

export default DependentVariables;
