// angular/src/app/app.component.ts
import { Component } from '@angular/core';

enum Components {
  HelloWorld,
  Styling,
  NestingComponents,
  Props,
  HTML,
  BasicVariables,
  DependentVariables,
  ConditionalRendering,
  ListLooping
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular';
  currentComponent: Components;

  constructor() {
    this.currentComponent = Components.HelloWorld;
  }

  handleSwitch(newComponent: Components) {
		this.currentComponent = newComponent;
	};
}

<div class="container">
  <nav class="links">
    <button (click)="handleSwitch(0)">Hello World</button>
    <button (click)="handleSwitch(1)">Styling</button>
    <button (click)="handleSwitch(2)">Nesting Components</button>
    <button (click)="handleSwitch(3)">Props</button>
    <button (click)="handleSwitch(4)">HTML Tags</button>
    <button (click)="handleSwitch(5)">Basic Variables</button>
    <button (click)="handleSwitch(6)">Dependent Variables</button>
    <button (click)="handleSwitch(7)">Conditional Rendering</button>
    <button (click)="handleSwitch(8)">List Looping</button>
  </nav>
  <div class="components">
    <app-hello-world *ngIf="currentComponent===0"></app-hello-world>
    <app-styling *ngIf="currentComponent===1"></app-styling>
    <app-nesting-components *ngIf="currentComponent===2"></app-nesting-components>
    <app-props *ngIf="currentComponent===3"></app-props>
    <app-html *ngIf="currentComponent===4"><strong>HTML!!!</strong></app-html>
    <app-basic-variables *ngIf="currentComponent===5"></app-basic-variables>
    <app-dependent-variables *ngIf="currentComponent===6"></app-dependent-variables>
    <app-conditional-rendering *ngIf="currentComponent===7"></app-conditional-rendering>
    <app-list-looping *ngIf="currentComponent===8"></app-list-looping>
  </div>
</div>

// solid/src/App.tsx
import { Component, createSignal, Match, Switch } from "solid-js";

import styles from "./App.module.css";
import {
  BasicVariables,
  ConditionalRendering,
  DependentVariables,
  HelloWorld,
  ListLooping,
  NestingComponents,
  Props,
  Styling,
} from "./components";

enum Components {
  HelloWorld,
  Styling,
  NestingComponents,
  HTML,
  BasicVariables,
  DependentVariables,
  Props,
  ConditionalRendering,
  ListLooping,
}

const App: Component = () => {
  const [currentComponent, setCurrentComponent] = createSignal<Components>(
    Components.HelloWorld
  );

  const handleSwitch = (newComponent: Components) => {
    setCurrentComponent(newComponent);
  };

  return (
    <div class={styles.container}>
      <nav className={styles.links}>
        <button onClick={() => handleSwitch(Components.HelloWorld)}>
          Hello World
        </button>
        <button onClick={() => handleSwitch(Components.Styling)}>
          Styling
        </button>
        <button onClick={() => handleSwitch(Components.NestingComponents)}>
          Nesting Components
        </button>
        <button onClick={() => handleSwitch(Components.HTML)}>HTML Tags</button>
        <button onClick={() => handleSwitch(Components.BasicVariables)}>
          Basic Variables
        </button>
        <button onClick={() => handleSwitch(Components.DependentVariables)}>
          Dependent Variables
        </button>
        <button onClick={() => handleSwitch(Components.Props)}>Props</button>
        <button onClick={() => handleSwitch(Components.ConditionalRendering)}>
          Conditional Rendering
        </button>
        <button onClick={() => handleSwitch(Components.ListLooping)}>
          List Looping
        </button>
      </nav>
      <div className={styles.components}>
        <Switch fallback={<p>Switch is out of range</p>}>
          <Match when={currentComponent() === Components.HelloWorld}>
            <HelloWorld />
          </Match>
          <Match when={currentComponent() === Components.Styling}>
            <Styling />
          </Match>
          <Match when={currentComponent() === Components.NestingComponents}>
            <NestingComponents />
          </Match>
          <Match when={currentComponent() === Components.HTML}>
            <p>To be determined</p>
          </Match>
          <Match when={currentComponent() === Components.BasicVariables}>
            <BasicVariables />
          </Match>
          <Match when={currentComponent() === Components.Props}>
            <Props />
          </Match>
          <Match when={currentComponent() === Components.DependentVariables}>
            <DependentVariables />
          </Match>
          <Match when={currentComponent() === Components.ConditionalRendering}>
            <ConditionalRendering />
          </Match>
          <Match when={currentComponent() === Components.ListLooping}>
            <ListLooping />
          </Match>
        </Switch>
      </div>
    </div>
  );
};

export default App;
